const PRODUCTS=[
{id:"p01",name:"Windows Touchscreen POS",category:"Touch Screen POS",views:4,images:["assets/products/01-windows-touchscreen-pos/01-front-three-quarter.svg","assets/products/01-windows-touchscreen-pos/02-side-opposite-three-quarter.svg","assets/products/01-windows-touchscreen-pos/03-rear-connectivity-view.svg","assets/products/01-windows-touchscreen-pos/04-alternative-three-quarter-view.svg"]},
{id:"p02",name:"Android Touchscreen POS",category:"Touch Screen POS",views:4,images:["assets/products/02-android-touchscreen-pos/01-front-three-quarter.svg","assets/products/02-android-touchscreen-pos/02-side-three-quarter.svg","assets/products/02-android-touchscreen-pos/03-rear-connectivity-view.svg","assets/products/02-android-touchscreen-pos/04-alternative-three-quarter.svg"]},
{id:"p03",name:"Thermal Printer",category:"Thermal Printers",views:4,images:["assets/products/03-thermal-printer/01-front-three-quarter.svg","assets/products/03-thermal-printer/02-side-three-quarter.svg","assets/products/03-thermal-printer/03-rear-connectivity-view.svg","assets/products/03-thermal-printer/04-open-paper-mechanism.svg"]},
{id:"p04",name:"Barcode Scanner",category:"Barcode Scanners",views:3,images:["assets/products/04-barcode-scanner/01-front-three-quarter.svg","assets/products/04-barcode-scanner/02-side-opposite-three-quarter.svg","assets/products/04-barcode-scanner/03-rear-top-functional-view.svg"]},
{id:"p05",name:"Barcode Printer",category:"Barcode Printers",views:4,images:["assets/products/05-barcode-printer/01-front-three-quarter.svg","assets/products/05-barcode-printer/02-rear-three-quarter.svg","assets/products/05-barcode-printer/03-rear-connectivity-view.svg","assets/products/05-barcode-printer/04-open-label-mechanism-view.svg"]},
{id:"p07",name:"Cash Counting Machine",category:"Cash Counting",views:4,images:["assets/products/07-cash-counting-machine/01-front-three-quarter.svg","assets/products/07-cash-counting-machine/02-rear-three-quarter.svg","assets/products/07-cash-counting-machine/03-rear-connectivity-view.svg","assets/products/07-cash-counting-machine/04-open-functional-view.svg"]},
{id:"p08",name:"Barcode Labels",category:"Barcode Labels",views:1,images:["assets/products/08-barcode-labels/01-barcode-labels.svg"]},
{id:"p09",name:"Wax Ribbon Black",category:"Wax Ribbons",views:2,images:["assets/products/09-wax-ribbon-black/01-provided-wax-ribbon.svg","assets/products/09-wax-ribbon-black/02-provided-wax-ribbon.svg"]},
{id:"p10",name:"Cash Drawer",category:"Cash Drawers",views:3,images:["assets/products/10-cash-drawer/01-front-three-quarter.svg","assets/products/10-cash-drawer/02-opposite-three-quarter.svg","assets/products/10-cash-drawer/03-open-drawer-functional-view.svg"]},
{id:"p11",name:"Wax Ribbon Purple",category:"Wax Ribbons",views:3,images:["assets/products/11-wax-ribbon-purple/01-provided-wax-ribbon-purple.svg","assets/products/11-wax-ribbon-purple/02-provided-wax-ribbon-purple.svg","assets/products/11-wax-ribbon-purple/03-provided-wax-ribbon-purple.svg"]},
{id:"p12",name:"Computer System Desktop Setup",category:"Computer Systems",views:4,images:["assets/products/12-computer-system-desktop-setup/01-front-complete-desktop-setup.svg","assets/products/12-computer-system-desktop-setup/02-rear-three-quarter-view.svg","assets/products/12-computer-system-desktop-setup/03-rear-connectivity-view.svg","assets/products/12-computer-system-desktop-setup/04-underside-component-view.svg"]},
{id:"p13",name:"Billing Machine",category:"Billing Machines",views:4,images:["assets/products/13-billing-machine/01-front-three-quarter-view.svg","assets/products/13-billing-machine/02-rear-right-connectivity-view.svg","assets/products/13-billing-machine/03-rear-left-connectivity-view.svg","assets/products/13-billing-machine/04-underside-functional-view.svg"]}
];
function productImagePath(product,index=1){return product?.images?.[index-1]||"";}
