function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function galleryImages(product){return (window.LEARTECH_GALLERY&&window.LEARTECH_GALLERY[product.id])||[]}
function previewImage(product){return product.preview}
function productImagePath(product,index=1){const g=galleryImages(product);return g[index-1]?.src||previewImage(product)}
function card(p){return `<article class="card prod-card" data-product-id="${p.id}"><div class="product-image-link" data-product-id="${p.id}" tabindex="0" role="button"><div class="real-visual"><img src="${previewImage(p)}" alt="${esc(p.name)}" loading="lazy"></div></div><div class="body"><span class="tag">${esc(p.category)}</span><h3 style="margin-top:8px">${esc(p.name)}</h3><div class="rating" aria-label="Product gallery">★★★★★ <span style="color:#8292a7;font-size:12px">${p.views} photo${p.views===1?"":"s"}</span></div><div class="product-actions"><a class="btn outline" href="product.html?id=${p.id}">View Details</a><a class="btn primary" href="contact.html?product=${p.id}">Buy Now</a></div></div></article>`}
function loadGallery(product){return new Promise(resolve=>{window.LEARTECH_GALLERY=window.LEARTECH_GALLERY||{};if(window.LEARTECH_GALLERY[product.id])return resolve();const s=document.createElement("script");s.src="js/gallery-"+product.id+".js";s.onload=()=>{const key="LEARTECH_GALLERY_"+product.id;if(window[key])window.LEARTECH_GALLERY[product.id]=window[key];resolve()};s.onerror=resolve;document.head.appendChild(s)})}
function enhanceCardImages(){if(!("IntersectionObserver"in window))return;const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const img=entry.target.querySelector("img"),p=PRODUCTS.find(x=>x.id===entry.target.dataset.productId);if(!img||!p)return;loadGallery(p).then(()=>{const src=productImagePath(p,1);if(src)img.src=src});io.unobserve(entry.target)}),{rootMargin:"240px"});document.querySelectorAll(".prod-card").forEach(c=>io.observe(c))}
function render(){const g=document.getElementById("productsGrid"),c=document.getElementById("count");if(!g)return;const tab=document.querySelector(".tab[data-cat].active"),cat=tab?.dataset.cat||"All",cats=[...document.querySelectorAll(".catfilter:checked")].map(x=>x.value);let list=PRODUCTS.filter(p=>(cat==="All"||p.category===cat)&&(!cats.length||cats.includes(p.category)));const sort=document.getElementById("sort")?.value;if(sort==="Name: A-Z")list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==="Name: Z-A")list.sort((a,b)=>b.name.localeCompare(a.name));g.innerHTML=list.map(card).join("");if(c)c.textContent="("+list.length+")";enhanceCardImages()}
function initProductDetail(){const root=document.getElementById("page-product");if(!root)return;const p=PRODUCTS.find(x=>x.id===new URLSearchParams(location.search).get("id"))||PRODUCTS[0];loadGallery(p).then(()=>{const imgs=galleryImages(p),main=root.querySelector(".detail-photo"),set=(s,v)=>{const e=root.querySelector(s);if(e)e.textContent=v};set(".breadcrumb","Home › Products › "+p.category+" › "+p.name);set(".detail-copy .tag","Leartech");set(".detail-copy h1",p.name);if(main){main.src=productImagePath(p,1);main.alt=p.name}const gallery=root.querySelector(".gallery");if(!gallery)return;const strip=document.createElement("div");strip.className="gallery-thumbs";strip.innerHTML=imgs.map((item,i)=>`<button class="gallery-thumb ${i===0?"active":""}" type="button" data-index="${i+1}" aria-label="View ${i+1}"><img src="${item.src}" alt="${p.name} view ${i+1}" loading="lazy"></button>`).join("");const old=gallery.querySelector(".gallery-thumbs");if(old)old.remove();gallery.appendChild(strip);strip.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{strip.querySelectorAll("button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");if(main)main.src=imgs[Number(btn.dataset.index)-1].src}));const quote=root.querySelector("[data-product-quote]");if(quote)quote.href="contact.html?product="+encodeURIComponent(p.id);const wa=root.querySelector(".detail-copy a.btn.green");if(wa)wa.href="https://wa.me/918904997113?text="+encodeURIComponent("Hi Leartech, I am interested in "+p.name+". Please share the price and details.")})}
document.addEventListener("DOMContentLoaded",()=>{if(document.getElementById("productsGrid")){document.querySelectorAll(".tab[data-cat]").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab[data-cat]").forEach(x=>x.classList.remove("active"));t.classList.add("active");render()}));document.querySelectorAll(".catfilter,.brandfilter").forEach(x=>x.addEventListener("change",render));document.getElementById("sort")?.addEventListener("change",render);render()}const home=document.getElementById("homeProducts");if(home)home.innerHTML=PRODUCTS.slice(0,4).map(card).join("");initProductDetail()});

/* Final gallery loader: maps each product module to its lowercase product id. */
