function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function card(p){return `<article class="card prod-card" data-product-id="${p.id}">
<div class="real-visual"><img src="${productImagePath(p,1)}" alt="${esc(p.name)}" loading="lazy" decoding="async"></div>
<div class="body"><span class="tag">${esc(p.category)}</span><h3 style="margin-top:8px">${esc(p.name)}</h3>
<div class="rating" aria-label="${p.views} product photos">★★★★★ <span style="color:#8292a7;font-size:12px">${p.views} photo${p.views===1?"":"s"}</span></div>
<div class="product-actions"><a class="btn outline" href="product.html?id=${p.id}">View Details</a><a class="btn primary" href="contact.html?product=${p.id}">Buy Now</a></div>
</div></article>`}
function getList(){const tab=document.querySelector(".tab[data-cat].active"),cat=tab?.dataset.cat||"All",cats=[...document.querySelectorAll(".catfilter:checked")].map(x=>x.value);let list=PRODUCTS.filter(p=>(cat==="All"||p.category===cat)&&(!cats.length||cats.includes(p.category)));const sort=document.getElementById("sort")?.value;if(sort==="Name: A-Z")list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==="Name: Z-A")list.sort((a,b)=>b.name.localeCompare(a.name));return list}
function render(){const g=document.getElementById("productsGrid"),c=document.getElementById("count");if(!g)return;const list=getList();g.innerHTML=list.map(card).join("");if(c)c.textContent="("+list.length+")";document.querySelectorAll(".product-image-link,.real-visual").forEach(el=>el.addEventListener("click",()=>{const card=el.closest("[data-product-id]");if(card)location.href="product.html?id="+encodeURIComponent(card.dataset.productId)}))}
function initProductDetail(){const root=document.getElementById("page-product");if(!root)return;const p=PRODUCTS.find(x=>x.id===new URLSearchParams(location.search).get("id"))||PRODUCTS[0],set=(s,v)=>{const el=root.querySelector(s);if(el)el.textContent=v};const main=root.querySelector(".detail-photo"),thumbs=root.querySelector(".gallery-thumbs");set(".breadcrumb","Home › Products › "+p.category+" › "+p.name);set(".detail-copy .tag","Leartech");set(".detail-copy h1",p.name);if(main){main.src=productImagePath(p,1);main.alt=p.name;main.decoding="async";main.onerror=()=>{main.onerror=null;main.src="assets/products/"+p.folder+"/"+p.images[0]}}if(thumbs){thumbs.innerHTML=p.images.map((src,i)=>`<button class="gallery-thumb${i===0?" active":""}" type="button" data-index="${i}" aria-label="View photo ${i+1}"><img src="${src}" alt="" loading="lazy" decoding="async"></button>`).join("");thumbs.querySelectorAll(".gallery-thumb").forEach(btn=>btn.addEventListener("click",()=>{thumbs.querySelectorAll(".gallery-thumb").forEach(x=>x.classList.remove("active"));btn.classList.add("active");main.src=p.images[Number(btn.dataset.index)]}))}const quote=root.querySelector("[data-product-quote]");if(quote)quote.href="contact.html?product="+encodeURIComponent(p.id);const wa=root.querySelector(".detail-copy a.btn.green");if(wa)wa.href="https://wa.me/918904997113?text="+encodeURIComponent("Hi Leartech, I am interested in "+p.name+". Please share the price and details.")}
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".tab[data-cat]").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".tab[data-cat]").forEach(x=>x.classList.remove("active"));t.classList.add("active");render()}));document.querySelectorAll(".catfilter").forEach(x=>x.addEventListener("change",render));document.getElementById("sort")?.addEventListener("change",render);render();const home=document.getElementById("homeProducts");if(home)home.innerHTML=PRODUCTS.slice(0,4).map(card).join("");initProductDetail();});
